name: CI & Publish

on:
  push:
    branches:
      - main

env:
  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
jobs:
  build-publish:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: https://registry.npmjs.org

      - name: Enable Corepack
        run: |
          corepack enable
          corepack prepare yarn@stable --activate

      - name: Install dependencies
        run: yarn install --immutable

      - name: Lint
        run: yarn lint

      - name: Test
        run: yarn test

      - name: Build packages
        run: yarn build

      - name: Publish packages
        run: |
          yarn changeset publish
